/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CatalogosExample: typeof import('./src/components/examples/CatalogosExample.vue')['default']
    DireccionForm: typeof import('./src/components/forms/DireccionForm.vue')['default']
    DocumentosPersonal: typeof import('./src/components/personal/DocumentosPersonal.vue')['default']
    DocumentosProyecto: typeof import('./src/components/proyectos/DocumentosProyecto.vue')['default']
    EquipoBodegaPersonal: typeof import('./src/components/personal/EquipoBodegaPersonal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PermisosPersonal: typeof import('./src/components/personal/PermisosPersonal.vue')['default']
    PersonalSelector: typeof import('./src/components/planilla/PersonalSelector.vue')['default']
    PrestamosPersonal: typeof import('./src/components/personal/PrestamosPersonal.vue')['default']
    ReferenciasLaborales: typeof import('./src/components/personal/ReferenciasLaborales.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransaccionesPersonal: typeof import('./src/components/personal/TransaccionesPersonal.vue')['default']
    VacacionesPersonal: typeof import('./src/components/personal/VacacionesPersonal.vue')['default']
  }
}
